/*
  Simple DirectMedia Layer
  Copyright (C) 1997-2025 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

/**
 * # CategoryKeycode
 *
 * Defines constants which identify keyboard keys and modifiers.
 *
 * Please refer to the Best Keyboard Practices document for details on what
 * this information means and how best to use it.
 *
 * https://wiki.libsdl.org/SDL3/BestKeyboardPractices
 */

#pragma once

#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_scancode.h>

/**
 * The SDL virtual key representation.
 *
 * Values of this type are used to represent keyboard keys using the current
 * layout of the keyboard. These values include Unicode values representing
 * the unmodified character that would be generated by pressing the key, or an
 * `SDLK_*` constant for those keys that do not generate characters.
 *
 * A special exception is the number keys at the top of the keyboard which map
 * to SDLK_0...SDLK_9 on AZERTY layouts.
 *
 * Keys with the `SDLK_EXTENDED_MASK` bit set do not map to a scancode or
 * unicode code point.
 *
 * \since This datatype is available since SDL 3.2.0.
 */
typedef Uint32 DN_Keycode;

#define DN_KEY_EXTENDED_MASK          (1u << 29)
#define DN_KEY_SCANCODE_MASK          (1u << 30)
#define DN_SCANCODE_TO_DN_KEYCODE(X)  (X | DN_KEY_SCANCODE_MASK)
#define DN_KEY_UNKNOWN                0x00000000u /**< 0 */
#define DN_KEY_RETURN                 0x0000000du /**< '\r' */
#define DN_KEY_ESCAPE                 0x0000001bu /**< '\x1B' */
#define DN_KEY_BACKSPACE              0x00000008u /**< '\b' */
#define DN_KEY_TAB                    0x00000009u /**< '\t' */
#define DN_KEY_SPACE                  0x00000020u /**< ' ' */
#define DN_KEY_EXCLAIM                0x00000021u /**< '!' */
#define DN_KEY_DBLAPOSTROPHE          0x00000022u /**< '"' */
#define DN_KEY_HASH                   0x00000023u /**< '#' */
#define DN_KEY_DOLLAR                 0x00000024u /**< '$' */
#define DN_KEY_PERCENT                0x00000025u /**< '%' */
#define DN_KEY_AMPERSAND              0x00000026u /**< '&' */
#define DN_KEY_APOSTROPHE             0x00000027u /**< '\'' */
#define DN_KEY_LEFTPAREN              0x00000028u /**< '(' */
#define DN_KEY_RIGHTPAREN             0x00000029u /**< ')' */
#define DN_KEY_ASTERISK               0x0000002au /**< '*' */
#define DN_KEY_PLUS                   0x0000002bu /**< '+' */
#define DN_KEY_COMMA                  0x0000002cu /**< ',' */
#define DN_KEY_MINUS                  0x0000002du /**< '-' */
#define DN_KEY_PERIOD                 0x0000002eu /**< '.' */
#define DN_KEY_SLASH                  0x0000002fu /**< '/' */
#define DN_KEY_0                      0x00000030u /**< '0' */
#define DN_KEY_1                      0x00000031u /**< '1' */
#define DN_KEY_2                      0x00000032u /**< '2' */
#define DN_KEY_3                      0x00000033u /**< '3' */
#define DN_KEY_4                      0x00000034u /**< '4' */
#define DN_KEY_5                      0x00000035u /**< '5' */
#define DN_KEY_6                      0x00000036u /**< '6' */
#define DN_KEY_7                      0x00000037u /**< '7' */
#define DN_KEY_8                      0x00000038u /**< '8' */
#define DN_KEY_9                      0x00000039u /**< '9' */
#define DN_KEY_COLON                  0x0000003au /**< ':' */
#define DN_KEY_SEMICOLON              0x0000003bu /**< ';' */
#define DN_KEY_LESS                   0x0000003cu /**< '<' */
#define DN_KEY_EQUALS                 0x0000003du /**< '=' */
#define DN_KEY_GREATER                0x0000003eu /**< '>' */
#define DN_KEY_QUESTION               0x0000003fu /**< '?' */
#define DN_KEY_AT                     0x00000040u /**< '@' */
#define DN_KEY_LEFTBRACKET            0x0000005bu /**< '[' */
#define DN_KEY_BACKSLASH              0x0000005cu /**< '\\' */
#define DN_KEY_RIGHTBRACKET           0x0000005du /**< ']' */
#define DN_KEY_CARET                  0x0000005eu /**< '^' */
#define DN_KEY_UNDERSCORE             0x0000005fu /**< '_' */
#define DN_KEY_GRAVE                  0x00000060u /**< '`' */
#define DN_KEY_A                      0x00000061u /**< 'a' */
#define DN_KEY_B                      0x00000062u /**< 'b' */
#define DN_KEY_C                      0x00000063u /**< 'c' */
#define DN_KEY_D                      0x00000064u /**< 'd' */
#define DN_KEY_E                      0x00000065u /**< 'e' */
#define DN_KEY_F                      0x00000066u /**< 'f' */
#define DN_KEY_G                      0x00000067u /**< 'g' */
#define DN_KEY_H                      0x00000068u /**< 'h' */
#define DN_KEY_I                      0x00000069u /**< 'i' */
#define DN_KEY_J                      0x0000006au /**< 'j' */
#define DN_KEY_K                      0x0000006bu /**< 'k' */
#define DN_KEY_L                      0x0000006cu /**< 'l' */
#define DN_KEY_M                      0x0000006du /**< 'm' */
#define DN_KEY_N                      0x0000006eu /**< 'n' */
#define DN_KEY_O                      0x0000006fu /**< 'o' */
#define DN_KEY_P                      0x00000070u /**< 'p' */
#define DN_KEY_Q                      0x00000071u /**< 'q' */
#define DN_KEY_R                      0x00000072u /**< 'r' */
#define DN_KEY_S                      0x00000073u /**< 's' */
#define DN_KEY_T                      0x00000074u /**< 't' */
#define DN_KEY_U                      0x00000075u /**< 'u' */
#define DN_KEY_V                      0x00000076u /**< 'v' */
#define DN_KEY_W                      0x00000077u /**< 'w' */
#define DN_KEY_X                      0x00000078u /**< 'x' */
#define DN_KEY_Y                      0x00000079u /**< 'y' */
#define DN_KEY_Z                      0x0000007au /**< 'z' */
#define DN_KEY_LEFTBRACE              0x0000007bu /**< '{' */
#define DN_KEY_PIPE                   0x0000007cu /**< '|' */
#define DN_KEY_RIGHTBRACE             0x0000007du /**< '}' */
#define DN_KEY_TILDE                  0x0000007eu /**< '~' */
#define DN_KEY_DELETE                 0x0000007fu /**< '\x7F' */
#define DN_KEY_PLUSMINUS              0x000000b1u /**< '\xB1' */
#define DN_KEY_CAPSLOCK               0x40000039u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CAPSLOCK) */
#define DN_KEY_F1                     0x4000003au /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F1) */
#define DN_KEY_F2                     0x4000003bu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F2) */
#define DN_KEY_F3                     0x4000003cu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F3) */
#define DN_KEY_F4                     0x4000003du /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F4) */
#define DN_KEY_F5                     0x4000003eu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F5) */
#define DN_KEY_F6                     0x4000003fu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F6) */
#define DN_KEY_F7                     0x40000040u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F7) */
#define DN_KEY_F8                     0x40000041u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F8) */
#define DN_KEY_F9                     0x40000042u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F9) */
#define DN_KEY_F10                    0x40000043u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F10) */
#define DN_KEY_F11                    0x40000044u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F11) */
#define DN_KEY_F12                    0x40000045u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F12) */
#define DN_KEY_PRINTSCREEN            0x40000046u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_PRINTSCREEN) */
#define DN_KEY_SCROLLLOCK             0x40000047u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_SCROLLLOCK) */
#define DN_KEY_PAUSE                  0x40000048u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_PAUSE) */
#define DN_KEY_INSERT                 0x40000049u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_INSERT) */
#define DN_KEY_HOME                   0x4000004au /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_HOME) */
#define DN_KEY_PAGEUP                 0x4000004bu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_PAGEUP) */
#define DN_KEY_END                    0x4000004du /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_END) */
#define DN_KEY_PAGEDOWN               0x4000004eu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_PAGEDOWN) */
#define DN_KEY_RIGHT                  0x4000004fu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_RIGHT) */
#define DN_KEY_LEFT                   0x40000050u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_LEFT) */
#define DN_KEY_DOWN                   0x40000051u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_DOWN) */
#define DN_KEY_UP                     0x40000052u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_UP) */
#define DN_KEY_NUMLOCKCLEAR           0x40000053u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR) */
#define DN_KEY_KP_DIVIDE              0x40000054u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_DIVIDE) */
#define DN_KEY_KP_MULTIPLY            0x40000055u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_MULTIPLY) */
#define DN_KEY_KP_MINUS               0x40000056u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_MINUS) */
#define DN_KEY_KP_PLUS                0x40000057u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_PLUS) */
#define DN_KEY_KP_ENTER               0x40000058u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_ENTER) */
#define DN_KEY_KP_1                   0x40000059u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_1) */
#define DN_KEY_KP_2                   0x4000005au /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_2) */
#define DN_KEY_KP_3                   0x4000005bu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_3) */
#define DN_KEY_KP_4                   0x4000005cu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_4) */
#define DN_KEY_KP_5                   0x4000005du /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_5) */
#define DN_KEY_KP_6                   0x4000005eu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_6) */
#define DN_KEY_KP_7                   0x4000005fu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_7) */
#define DN_KEY_KP_8                   0x40000060u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_8) */
#define DN_KEY_KP_9                   0x40000061u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_9) */
#define DN_KEY_KP_0                   0x40000062u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_0) */
#define DN_KEY_KP_PERIOD              0x40000063u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_PERIOD) */
#define DN_KEY_APPLICATION            0x40000065u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_APPLICATION) */
#define DN_KEY_POWER                  0x40000066u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_POWER) */
#define DN_KEY_KP_EQUALS              0x40000067u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_EQUALS) */
#define DN_KEY_F13                    0x40000068u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F13) */
#define DN_KEY_F14                    0x40000069u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F14) */
#define DN_KEY_F15                    0x4000006au /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F15) */
#define DN_KEY_F16                    0x4000006bu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F16) */
#define DN_KEY_F17                    0x4000006cu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F17) */
#define DN_KEY_F18                    0x4000006du /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F18) */
#define DN_KEY_F19                    0x4000006eu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F19) */
#define DN_KEY_F20                    0x4000006fu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F20) */
#define DN_KEY_F21                    0x40000070u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F21) */
#define DN_KEY_F22                    0x40000071u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F22) */
#define DN_KEY_F23                    0x40000072u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F23) */
#define DN_KEY_F24                    0x40000073u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_F24) */
#define DN_KEY_EXECUTE                0x40000074u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_EXECUTE) */
#define DN_KEY_HELP                   0x40000075u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_HELP) */
#define DN_KEY_MENU                   0x40000076u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MENU) */
#define DN_KEY_SELECT                 0x40000077u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_SELECT) */
#define DN_KEY_STOP                   0x40000078u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_STOP) */
#define DN_KEY_AGAIN                  0x40000079u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AGAIN) */
#define DN_KEY_UNDO                   0x4000007au /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_UNDO) */
#define DN_KEY_CUT                    0x4000007bu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CUT) */
#define DN_KEY_COPY                   0x4000007cu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_COPY) */
#define DN_KEY_PASTE                  0x4000007du /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_PASTE) */
#define DN_KEY_FIND                   0x4000007eu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_FIND) */
#define DN_KEY_MUTE                   0x4000007fu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MUTE) */
#define DN_KEY_VOLUMEUP               0x40000080u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_VOLUMEUP) */
#define DN_KEY_VOLUMEDOWN             0x40000081u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_VOLUMEDOWN) */
#define DN_KEY_KP_COMMA               0x40000085u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_COMMA) */
#define DN_KEY_KP_EQUALSAS400         0x40000086u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400) */
#define DN_KEY_ALTERASE               0x40000099u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_ALTERASE) */
#define DN_KEY_SYSREQ                 0x4000009au /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_SYSREQ) */
#define DN_KEY_CANCEL                 0x4000009bu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CANCEL) */
#define DN_KEY_CLEAR                  0x4000009cu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CLEAR) */
#define DN_KEY_PRIOR                  0x4000009du /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_PRIOR) */
#define DN_KEY_RETURN2                0x4000009eu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_RETURN2) */
#define DN_KEY_SEPARATOR              0x4000009fu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_SEPARATOR) */
#define DN_KEY_OUT                    0x400000a0u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_OUT) */
#define DN_KEY_OPER                   0x400000a1u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_OPER) */
#define DN_KEY_CLEARAGAIN             0x400000a2u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CLEARAGAIN) */
#define DN_KEY_CRSEL                  0x400000a3u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CRSEL) */
#define DN_KEY_EXSEL                  0x400000a4u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_EXSEL) */
#define DN_KEY_KP_00                  0x400000b0u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_00) */
#define DN_KEY_KP_000                 0x400000b1u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_000) */
#define DN_KEY_THOUSANDSSEPARATOR     0x400000b2u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR) */
#define DN_KEY_DECIMALSEPARATOR       0x400000b3u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR) */
#define DN_KEY_CURRENCYUNIT           0x400000b4u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CURRENCYUNIT) */
#define DN_KEY_CURRENCYSUBUNIT        0x400000b5u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT) */
#define DN_KEY_KP_LEFTPAREN           0x400000b6u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN) */
#define DN_KEY_KP_RIGHTPAREN          0x400000b7u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN) */
#define DN_KEY_KP_LEFTBRACE           0x400000b8u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE) */
#define DN_KEY_KP_RIGHTBRACE          0x400000b9u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE) */
#define DN_KEY_KP_TAB                 0x400000bau /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_TAB) */
#define DN_KEY_KP_BACKSPACE           0x400000bbu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_BACKSPACE) */
#define DN_KEY_KP_A                   0x400000bcu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_A) */
#define DN_KEY_KP_B                   0x400000bdu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_B) */
#define DN_KEY_KP_C                   0x400000beu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_C) */
#define DN_KEY_KP_D                   0x400000bfu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_D) */
#define DN_KEY_KP_E                   0x400000c0u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_E) */
#define DN_KEY_KP_F                   0x400000c1u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_F) */
#define DN_KEY_KP_XOR                 0x400000c2u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_XOR) */
#define DN_KEY_KP_POWER               0x400000c3u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_POWER) */
#define DN_KEY_KP_PERCENT             0x400000c4u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_PERCENT) */
#define DN_KEY_KP_LESS                0x400000c5u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_LESS) */
#define DN_KEY_KP_GREATER             0x400000c6u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_GREATER) */
#define DN_KEY_KP_AMPERSAND           0x400000c7u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_AMPERSAND) */
#define DN_KEY_KP_DBLAMPERSAND        0x400000c8u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND) */
#define DN_KEY_KP_VERTICALBAR         0x400000c9u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR) */
#define DN_KEY_KP_DBLVERTICALBAR      0x400000cau /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR) */
#define DN_KEY_KP_COLON               0x400000cbu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_COLON) */
#define DN_KEY_KP_HASH                0x400000ccu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_HASH) */
#define DN_KEY_KP_SPACE               0x400000cdu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_SPACE) */
#define DN_KEY_KP_AT                  0x400000ceu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_AT) */
#define DN_KEY_KP_EXCLAM              0x400000cfu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_EXCLAM) */
#define DN_KEY_KP_MEMSTORE            0x400000d0u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_MEMSTORE) */
#define DN_KEY_KP_MEMRECALL           0x400000d1u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_MEMRECALL) */
#define DN_KEY_KP_MEMCLEAR            0x400000d2u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR) */
#define DN_KEY_KP_MEMADD              0x400000d3u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_MEMADD) */
#define DN_KEY_KP_MEMSUBTRACT         0x400000d4u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT) */
#define DN_KEY_KP_MEMMULTIPLY         0x400000d5u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY) */
#define DN_KEY_KP_MEMDIVIDE           0x400000d6u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE) */
#define DN_KEY_KP_PLUSMINUS           0x400000d7u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS) */
#define DN_KEY_KP_CLEAR               0x400000d8u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_CLEAR) */
#define DN_KEY_KP_CLEARENTRY          0x400000d9u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY) */
#define DN_KEY_KP_BINARY              0x400000dau /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_BINARY) */
#define DN_KEY_KP_OCTAL               0x400000dbu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_OCTAL) */
#define DN_KEY_KP_DECIMAL             0x400000dcu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_DECIMAL) */
#define DN_KEY_KP_HEXADECIMAL         0x400000ddu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL) */
#define DN_KEY_LCTRL                  0x400000e0u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_LCTRL) */
#define DN_KEY_LSHIFT                 0x400000e1u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_LSHIFT) */
#define DN_KEY_LALT                   0x400000e2u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_LALT) */
#define DN_KEY_LGUI                   0x400000e3u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_LGUI) */
#define DN_KEY_RCTRL                  0x400000e4u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_RCTRL) */
#define DN_KEY_RSHIFT                 0x400000e5u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_RSHIFT) */
#define DN_KEY_RALT                   0x400000e6u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_RALT) */
#define DN_KEY_RGUI                   0x400000e7u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_RGUI) */
#define DN_KEY_MODE                   0x40000101u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MODE) */
#define DN_KEY_SLEEP                  0x40000102u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_SLEEP) */
#define DN_KEY_WAKE                   0x40000103u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_WAKE) */
#define DN_KEY_CHANNEL_INCREMENT      0x40000104u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CHANNEL_INCREMENT) */
#define DN_KEY_CHANNEL_DECREMENT      0x40000105u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CHANNEL_DECREMENT) */
#define DN_KEY_MEDIA_PLAY             0x40000106u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_PLAY) */
#define DN_KEY_MEDIA_PAUSE            0x40000107u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_PAUSE) */
#define DN_KEY_MEDIA_RECORD           0x40000108u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_RECORD) */
#define DN_KEY_MEDIA_FAST_FORWARD     0x40000109u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_FAST_FORWARD) */
#define DN_KEY_MEDIA_REWIND           0x4000010au /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_REWIND) */
#define DN_KEY_MEDIA_NEXT_TRACK       0x4000010bu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_NEXT_TRACK) */
#define DN_KEY_MEDIA_PREVIOUS_TRACK   0x4000010cu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_PREVIOUS_TRACK) */
#define DN_KEY_MEDIA_STOP             0x4000010du /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_STOP) */
#define DN_KEY_MEDIA_EJECT            0x4000010eu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_EJECT) */
#define DN_KEY_MEDIA_PLAY_PAUSE       0x4000010fu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_PLAY_PAUSE) */
#define DN_KEY_MEDIA_SELECT           0x40000110u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_MEDIA_SELECT) */
#define DN_KEY_AC_NEW                 0x40000111u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_NEW) */
#define DN_KEY_AC_OPEN                0x40000112u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_OPEN) */
#define DN_KEY_AC_CLOSE               0x40000113u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_CLOSE) */
#define DN_KEY_AC_EXIT                0x40000114u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_EXIT) */
#define DN_KEY_AC_SAVE                0x40000115u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_SAVE) */
#define DN_KEY_AC_PRINT               0x40000116u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_PRINT) */
#define DN_KEY_AC_PROPERTIES          0x40000117u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_PROPERTIES) */
#define DN_KEY_AC_SEARCH              0x40000118u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_SEARCH) */
#define DN_KEY_AC_HOME                0x40000119u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_HOME) */
#define DN_KEY_AC_BACK                0x4000011au /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_BACK) */
#define DN_KEY_AC_FORWARD             0x4000011bu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_FORWARD) */
#define DN_KEY_AC_STOP                0x4000011cu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_STOP) */
#define DN_KEY_AC_REFRESH             0x4000011du /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_REFRESH) */
#define DN_KEY_AC_BOOKMARKS           0x4000011eu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS) */
#define DN_KEY_SOFTLEFT               0x4000011fu /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_SOFTLEFT) */
#define DN_KEY_SOFTRIGHT              0x40000120u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_SOFTRIGHT) */
#define DN_KEY_CALL                   0x40000121u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_CALL) */
#define DN_KEY_ENDCALL                0x40000122u /**< DN_SCANCODE_TO_DN_KEYCODE(SDL_SCANCODE_ENDCALL) */
#define DN_KEY_LEFT_TAB               0x20000001u /**< Extended key Left Tab */
#define DN_KEY_LEVEL5_SHIFT           0x20000002u /**< Extended key Level 5 Shift */
#define DN_KEY_MULTI_DN_KEY_COMPOSE      0x20000003u /**< Extended key Multi-key Compose */
#define DN_KEY_LMETA                  0x20000004u /**< Extended key Left Meta */
#define DN_KEY_RMETA                  0x20000005u /**< Extended key Right Meta */
#define DN_KEY_LHYPER                 0x20000006u /**< Extended key Left Hyper */
#define DN_KEY_RHYPER                 0x20000007u /**< Extended key Right Hyper */

/**
 * Valid key modifiers (possibly OR'd together).
 *
 * \since This datatype is available since SDL 3.2.0.
 */
typedef Uint16 DN_Keymod;

#define DN_KEY_MOD_NONE   0x0000u /**< no modifier is applicable. */
#define DN_KEY_MOD_LSHIFT 0x0001u /**< the left Shift key is down. */
#define DN_KEY_MOD_RSHIFT 0x0002u /**< the right Shift key is down. */
#define DN_KEY_MOD_LEVEL5 0x0004u /**< the Level 5 Shift key is down. */
#define DN_KEY_MOD_LCTRL  0x0040u /**< the left Ctrl (Control) key is down. */
#define DN_KEY_MOD_RCTRL  0x0080u /**< the right Ctrl (Control) key is down. */
#define DN_KEY_MOD_LALT   0x0100u /**< the left Alt key is down. */
#define DN_KEY_MOD_RALT   0x0200u /**< the right Alt key is down. */
#define DN_KEY_MOD_LGUI   0x0400u /**< the left GUI key (often the Windows key) is down. */
#define DN_KEY_MOD_RGUI   0x0800u /**< the right GUI key (often the Windows key) is down. */
#define DN_KEY_MOD_NUM    0x1000u /**< the Num Lock key (may be located on an extended keypad) is down. */
#define DN_KEY_MOD_CAPS   0x2000u /**< the Caps Lock key is down. */
#define DN_KEY_MOD_MODE   0x4000u /**< the !AltGr key is down. */
#define DN_KEY_MOD_SCROLL 0x8000u /**< the Scroll Lock key is down. */
#define DN_KEY_MOD_CTRL   (DN_KEY_MOD_LCTRL | DN_KEY_MOD_RCTRL)   /**< Any Ctrl key is down. */
#define DN_KEY_MOD_SHIFT  (DN_KEY_MOD_LSHIFT | DN_KEY_MOD_RSHIFT) /**< Any Shift key is down. */
#define DN_KEY_MOD_ALT    (DN_KEY_MOD_LALT | DN_KEY_MOD_RALT)     /**< Any Alt key is down. */
#define DN_KEY_MOD_GUI    (DN_KEY_MOD_LGUI | DN_KEY_MOD_RGUI)     /**< Any GUI key is down. */

