var hierarchy =
[
    [ "duin::ECSTag::ActiveCamera", "structduin_1_1_e_c_s_tag_1_1_active_camera.html", null ],
    [ "duin::ECSTag::ActiveExternalRef", "structduin_1_1_e_c_s_tag_1_1_active_external_ref.html", null ],
    [ "duin::Application", "classduin_1_1_application.html", null ],
    [ "duin::AssetManager", "classduin_1_1_asset_manager.html", null ],
    [ "duin::ECSTag::CameraIsActive", "structduin_1_1_e_c_s_tag_1_1_camera_is_active.html", null ],
    [ "duin::ECSComponent::CharacterBody3DComponent", "structduin_1_1_e_c_s_component_1_1_character_body3_d_component.html", null ],
    [ "duin::CharacterBody3DDesc", "structduin_1_1_character_body3_d_desc.html", null ],
    [ "duin::CharacterCollisionBody3D", "classduin_1_1_character_collision_body3_d.html", null ],
    [ "duin::ECSTag::CreateExternalRef", "structduin_1_1_e_c_s_tag_1_1_create_external_ref.html", null ],
    [ "spdlog::custom_flag_formatter", null, [
      [ "duin::FrameCountFormatter", "classduin_1_1_frame_count_formatter.html", null ]
    ] ],
    [ "duin::ECSComponent::DebugCapsuleComponent", "structduin_1_1_e_c_s_component_1_1_debug_capsule_component.html", null ],
    [ "duin::DebugConsole", "classduin_1_1_debug_console.html", null ],
    [ "duin::DebugWatchlist", "classduin_1_1_debug_watchlist.html", null ],
    [ "duin::ECSTag::DeleteExternalRef", "structduin_1_1_e_c_s_tag_1_1_delete_external_ref.html", null ],
    [ "duin::DynamicCollisionBody3D", "classduin_1_1_dynamic_collision_body3_d.html", null ],
    [ "duin::ECSManager", "classduin_1_1_e_c_s_manager.html", null ],
    [ "duin::float16", "structduin_1_1float16.html", null ],
    [ "duin::float3", "structduin_1_1float3.html", null ],
    [ "duin::GameObject", "classduin_1_1_game_object.html", null ],
    [ "duin::GameState", "classduin_1_1_game_state.html", null ],
    [ "duin::GameStateMachine", "classduin_1_1_game_state_machine.html", null ],
    [ "duin::ECSTag::Global", "structduin_1_1_e_c_s_tag_1_1_global.html", null ],
    [ "std::hash< duin::UUID >", "structstd_1_1hash_3_01duin_1_1_u_u_i_d_01_4.html", null ],
    [ "InputVector2DKeys", "struct_input_vector2_d_keys.html", null ],
    [ "duin::JSONDocument", "classduin_1_1_j_s_o_n_document.html", null ],
    [ "duin::JSONMember", "classduin_1_1_j_s_o_n_member.html", null ],
    [ "duin::ECSTag::Local", "structduin_1_1_e_c_s_tag_1_1_local.html", null ],
    [ "duin::Log", "classduin_1_1_log.html", null ],
    [ "duin::Matrix", "structduin_1_1_matrix.html", null ],
    [ "duin::ECSTag::NonPx", "structduin_1_1_e_c_s_tag_1_1_non_px.html", null ],
    [ "duin::Physics3DServer", "classduin_1_1_physics3_d_server.html", null ],
    [ "duin::PhysicsMaterial", "structduin_1_1_physics_material.html", null ],
    [ "duin::ECSComponent::Position2D", "structduin_1_1_e_c_s_component_1_1_position2_d.html", null ],
    [ "duin::ECSComponent::Position3D", "structduin_1_1_e_c_s_component_1_1_position3_d.html", null ],
    [ "duin::ECSTag::PxDynamic", "structduin_1_1_e_c_s_tag_1_1_px_dynamic.html", null ],
    [ "duin::ECSTag::PxKinematic", "structduin_1_1_e_c_s_tag_1_1_px_kinematic.html", null ],
    [ "duin::ECSTag::PxStatic", "structduin_1_1_e_c_s_tag_1_1_px_static.html", null ],
    [ "physx::PxUserControllerHitReport", null, [
      [ "duin::ControllerHitReport", "classduin_1_1_controller_hit_report.html", null ]
    ] ],
    [ "duin::ECSComponent::Rotation2D", "structduin_1_1_e_c_s_component_1_1_rotation2_d.html", null ],
    [ "duin::ECSComponent::Rotation3D", "structduin_1_1_e_c_s_component_1_1_rotation3_d.html", null ],
    [ "duin::ECSComponent::Scale2D", "structduin_1_1_e_c_s_component_1_1_scale2_d.html", null ],
    [ "duin::ECSComponent::Scale3D", "structduin_1_1_e_c_s_component_1_1_scale3_d.html", null ],
    [ "duin::ECSTag::SetCameraAsActive", "structduin_1_1_e_c_s_tag_1_1_set_camera_as_active.html", null ],
    [ "SM_Machine", "struct_s_m___machine.html", null ],
    [ "SM_State", "struct_s_m___state.html", null ],
    [ "duin::StaticCollisionBody3D", "classduin_1_1_static_collision_body3_d.html", null ],
    [ "duin::StaticCollisionPlane", "classduin_1_1_static_collision_plane.html", null ],
    [ "duin::StaticCollisionPlaneDesc", "structduin_1_1_static_collision_plane_desc.html", null ],
    [ "duin::UUID", "classduin_1_1_u_u_i_d.html", null ],
    [ "UUID", "struct_u_u_i_d.html", null ],
    [ "duin::Vector2", "structduin_1_1_vector2.html", null ],
    [ "duin::Vector3", "structduin_1_1_vector3.html", null ],
    [ "duin::Vector4", "structduin_1_1_vector4.html", null ],
    [ "duin::ECSComponent::Velocity2D", "structduin_1_1_e_c_s_component_1_1_velocity2_d.html", null ],
    [ "duin::ECSComponent::Velocity3D", "structduin_1_1_e_c_s_component_1_1_velocity3_d.html", null ]
];