name: Deploy Doxygen Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger when pushing to the source branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the source branch
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main  # Always use the source branch for building docs
        submodules: false

    # 2. Install Doxygen and Graphviz
    - name: Install Doxygen and Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    # 3. Copy custom files
    - name: Copy custom Doxygen files
      run: |
        echo '<html><head><script type="text/javascript" src="$relpath^doxygen-awesome-paragraph-link.js"></script><script type="text/javascript">DoxygenAwesomeParagraphLink.init()</script></head><body>' > ./Duin/doxygen/html/header.html

    # 4. Generate Documentation
    - name: Generate Documentation
      if: github.ref_name != 'docs'  # Skip if push originates from docs branch
      run: cd Duin && doxygen Doxyfile

    # 5. Deploy to the "docs" branch
    - name: Deploy to GitHub Pages
      if: startsWith(github.ref, 'refs/heads/main')
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: docs         # Deploy to the "docs" branch
        publish_dir: ./Duin/doxygen    # Directory where Doxygen outputs the HTML

