name: Deploy Doxygen Documentation to GitHub Pages

on:
  push:
    branches:
      - engine-overhaul  # Trigger when pushing to the source branch
      - docs             # Trigger when pushing to the docs branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the source branch
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: engine-overhaul  # Always use the source branch for building docs
        submodules: false

    # 2. Install Doxygen
    - name: Install Doxygen
      run: sudo apt-get install doxygen -y

    # 3. Generate Documentation
    - name: Generate Documentation
      if: github.ref_name != 'docs'  # Skip if push originates from docs branch
      run: cd Duin && doxygen Doxyfile

    # 4. Deploy to the "docs" branch
    - name: Deploy to GitHub Pages
      if: github.ref_name != 'docs'  # Skip deployment if already on docs branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: docs         # Deploy to the "docs" branch
        publish_dir: ./docs    # Directory where Doxygen outputs the HTML
