name: Deploy GitHub Pages

on:
  push:
    branches:
      - docs  # Replace with your publishing branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Doxygen
      run: sudo apt-get install doxygen -y

    - name: Generate Documentation
      run: cd Duin && doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./docs
